import argparse
import csv

# Verified real 5-point literature variants only.
LITERATURE_FIVE_POINT = [
    {"name": "FAST-PETase (Lu et al. 2022)",
     "wild_type": "S;D;R;N;R",
     "mutation_type": "E;H;Q;K;A",
     "position_idx": "121,186,224,233,280"},
]


def mutation_set(wt, mut, pos):
    return frozenset(zip([int(p) for p in pos.split(",")], mut.split(";")))


def generate_quints(quads_csv_path, singles_pool_csv_path, output_path):
    with open(quads_csv_path) as f:
        quads = list(csv.DictReader(f))

    with open(singles_pool_csv_path) as f:
        singles = list(csv.DictReader(f))
        for s in singles:
            s["_pos"] = int(s["position_idx"].split(",")[0])

    quints = []
    seen = set()
    n_dupes = 0

    for quad in quads:
        quad_wt = quad["wild_type"].split(";")
        quad_mut = quad["mutation_type"].split(";")
        quad_pos = [int(p) for p in quad["position_idx"].split(",")]

        for single in singles:
            if single["_pos"] in quad_pos:
                continue

            wt = ";".join(quad_wt + [single["wild_type"]])
            mut = ";".join(quad_mut + [single["mutation_type"]])
            pos = ",".join(str(p) for p in quad_pos + [single["_pos"]])

            sig = mutation_set(wt, mut, pos)
            if sig in seen:
                n_dupes += 1
                continue
            seen.add(sig)

            quints.append({"wild_type": wt, "mutation_type": mut, "position_idx": pos,
                           "stability_score": 0.0, "protein_id": "6EQE",
                           "_source": "quad_extension"})

    # Force-append literature reference variants (skip if already generated)
    n_lit_added = 0
    for lit in LITERATURE_FIVE_POINT:
        sig = mutation_set(lit["wild_type"], lit["mutation_type"], lit["position_idx"])
        if sig in seen:
            print(f"[quints] {lit['name']} was already generated by extension -- not duplicated")
            continue
        seen.add(sig)
        quints.append({"wild_type": lit["wild_type"], "mutation_type": lit["mutation_type"],
                       "position_idx": lit["position_idx"], "stability_score": 0.0,
                       "protein_id": "6EQE", "_source": "literature_reference_variant"})
        n_lit_added += 1

    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["wild_type", "mutation_type", "position_idx",
                                                 "stability_score", "protein_id", "_source"])
        writer.writeheader()
        writer.writerows(quints)

    print(f"[quints] {len(quads)} validated quads x {len(singles)} singles")
    print(f"[quints] Duplicates removed (same 5-mutation set): {n_dupes}")
    print(f"[quints] Literature reference variants appended: {n_lit_added}")
    print(f"[quints] TOTAL 5-point candidates: {len(quints)} -> {output_path}")
    return output_path


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--quads_csv", type=str, default="results/validated_quad_pool.csv")
    ap.add_argument("--singles_pool_csv", type=str, default="results/building_block_pool.csv")
    ap.add_argument("--output", type=str, default="data/screening_round5_quints.csv")
    args = ap.parse_args()

    generate_quints(args.quads_csv, args.singles_pool_csv, args.output)